name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore ./src/NbaStats.Data/NbaStats.Data.csproj
    - name: Build
      run: dotnet build .\src\NbaStats.Data\NbaStats.Data.csproj --no-restore --configuration Release
    - name: Test
      run: dotnet test .\src\NbaStats.Data.Tests\NbaStats.Data.Tests.csproj --verbosity normal
    - name: publish
      uses: rohith/publish-nuget@v2
      with:
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
        PROJECT_FILEPATH: src/NbaStats.Data/NbaStats.Data.csproj
